
name: saglik_asist
description: TUBITAK 2204A AI Health Guardian
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  lucide_icons: ^0.321.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_generative_ai: ^0.4.0
  fl_chart: ^0.66.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  provider: ^6.1.1

flutter:
  uses-material-design: true
